language: java
jdk: oraclejdk8
sudo: required

services:
  - docker

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - sudo mvn clean package -Dmy.password=$DOCKER_PASS docker:build -s maven-settings.xml