language: java
jdk: oraclejdk8
sudo: required

services:
  - docker

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - docker login -u $DOCKER_USER -p $DOCKER_PASS
  - docker build -t cabuhob/ping-pong .
  - docker push cabuhob/ping-pong